#!/usr/bin/env bash
#
# tt.d - The daemon behind tt, stops/resumes the timetrace tracking on screen lock/unlock.
#
set -o nounset

CACHE_DIR="$HOME/.tt"
PIDFILE=/tmp/tt_daemon.pid
LOGFILE=/tmp/tt_daemon.log
DEBUG=true

cleanup() {
    log "daemon stopped ..."
    rm -f $PIDFILE
    trap - INT TERM EXIT
    exit
}

log() {
    if [[ "$DEBUG" == "true" ]]; then
        echo $(date +%Y-%m-%d\ %X) -- $USER -- "$@"
    else
        echo $(date +%Y-%m-%d\ %X) -- $USER -- "$@" >> $LOGFILE
    fi
}

if [ -e "$PIDFILE" ]; then
    if [ $# -eq 1 ]; then
        if [[ "$1" == "kill" ]]; then
            cleanup
        fi
    fi
    log $0 "already running ..."
    exit
fi

trap cleanup INT TERM EXIT

log "daemon started ..."

echo $$ > $PIDFILE

first_run=true
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" |
    while read line; do
        case "$line" in
            *"boolean true"*)
                if [[ "$first_run" == "true" ]]; then
                    first_run=false
                    log "session locked, pausing timetrace"
                    t_out=`tt pause`
                    log "tt output => $t_out"
                else
                    first_run=true
                fi;
                ;;
            *"boolean false"*)
                if [[ "$first_run" == "true" ]]; then
                    first_run=false
                    log "session unlocked, resuming timetrace"
                    t_out=`tt resume`
                    log "tt output => $t_out"
                else
                    first_run=true
                fi;
                ;;
        esac
    done

cleanup
